import img1 from './assets/rumtek.jpg';
import img2 from './assets/pemayangtse.jpg';
import img3 from './assets/tashiding.jpg';
const monasteries = [
  {
    id: 1,
    name: "Rumtek Monastery",
    location: "Gangtok, Sikkim, India",
    description:
      "Rumtek Monastery, also called the Dharmachakra Centre, is the largest monastery in Sikkim. It serves as the seat of the Karma Kagyu lineage and is famous for its beautiful architecture, vibrant festivals like the Cham dance, and extensive Tibetan Buddhist traditions.",
    tags: ["Buddhist, ", "Karma Kagyu, ", "cultural, ", "festival"],
    src : img1,
    year: "1966",
  },
  {
  id: 2,
  name: "Pemayangtse Monastery",
  location: "Pelling, West Sikkim, India",
  description:"Founded in the early 18th century, Pemayangtse is one of the oldest and most revered monasteries in Sikkim. Known for its exquisite murals and statues, it plays a vital role in preserving Buddhist culture and hosting major religious festivals.",
  tags: ["historic, ", "murals, ", "Buddhist, ", "festivals"],
  src : img2,
  year: "1705",
},
{
  id: 3,
  name: "Tashiding Monastery",
  location: "West Sikkim, India",
  description: "Tashiding Monastery is among the holiest monasteries in Sikkim, believed to be blessed by Guru Padmasambhava. It is renowned for the Bumchu festival where water from a sacred vase is used to predict prosperity for the year.",
  tags: ["sacred, ", "festival, ", "historic, "],
  src : img3 ,
  year: "1717",
},
{
    id: 4,
   name: "Sanga Choeling Monastery",
    location: "West Sikkim, India",
    description: "One of the oldest monasteries in Sikkim, founded in 1697. Located on a ridge above Pelling, it offers peaceful meditation settings and is known for preserving rare Buddhist scriptures and rituals.",
    tags: ["ancient, ", "meditation, ", "historic, "],
    src: img1,
    year: "1697",
  },
  {
    id: 5,
    name: "Lachen Monastery",
    location: "Lachen, North Sikkim, India",
    description: "Lachen Monastery is located in the serene village of Lachen in North Sikkim. It is an important spiritual hub for local communities, known for traditional festivals and Tibetan Buddhist teachings.",
    tags: ["remote, ", "local festivals, ", "spiritual, "],
    src: img2,
    year: "1858",
  },
  {
    id: 6,
    name: "Lachung Monastery",
    location: "Lachung, North Sikkim, India",
    description: "Located in the picturesque Lachung valley, this monastery is known for its vibrant community activities, peaceful surroundings, and beautiful views of the Himalayas.",
    tags: ["scenic, ", "community, ", "spiritual, "],
    src: img3,
    year: "1880",
  },
{
    id: 7,
    name: "Ralong Monastery",
    location: "Ralong, South Sikkim, India",
    description:
      "Ralong Monastery is famous for its colorful festivals and rituals deeply rooted in the local Buddhist culture. It serves as a spiritual and cultural center in South Sikkim.",
    tags: ["rituals, ", "community, ", "cultural"],
    src: img1,
    year: "1768",
  },
  {
    id: 8,
    name: "Kewzing Monastery",
    location: "Kewzing, South Sikkim, India",
    description:
      "Kewzing Monastery is a tranquil monastery nestled in lush surroundings. It is known for its serene environment, spiritual teachings, and community events.",
    tags: ["peaceful, ", "spiritual, ", "community"],
    src: img2,
    year: "1980",
  },
  {
    id: 9,
    name: "Ben Monastery",
    location: "South Sikkim, India",
    description:
      "Ben Monastery is a quiet Buddhist monastery preserving traditional practices and serving as a place for meditation and spiritual study.",
    tags: ["traditional, ", "meditation, ", "Buddhist"],
    src: img3,
    year: "1900",
  },
{
    id: 10,
    name: "Enchey Monastery",
    location: "Gangtok, Sikkim, India",
    description:
      "A historic monastery in the capital city, Enchey Monastery is known for its ancient murals, beautiful architecture, and lively festivals celebrating Tibetan Buddhism.",
    tags: ["ancient, ", "murals, ", "festival"],
    src: img1,
    year: "1909",
  },
  {
    id: 11,
    name: "Lingdum Monastery",
    location: "North Sikkim, India",
    description:
      "Also known as Ranka Monastery, Lingdum is a tranquil Buddhist monastery popular for meditation retreats and its peaceful Himalayan setting.",
    tags: ["tranquil, ", "meditation, ", "scenic"],
    src: img2,
    year: "1998",
  },
  {
    id: 12,
    name: "Tsuk La Khang Monastery",
    location: "East Sikkim, India",
    description:
      "Tsuk La Khang Monastery is a spiritual center in East Sikkim, known for its prayer ceremonies, Buddhist teachings, and community involvement.",
    tags: ["prayer, ", "teachings, ", "community"],
    src: img3,
    year: "1898",
  },
{
    id: 13,
    name: "Do Drul Chorten",
    location: "Gangtok, Sikkim, India",
    description:
      "One of the largest stupas in Sikkim, Do Drul Chorten is an important pilgrimage site housing hundreds of prayer wheels and hosting many religious festivals throughout the year.",
    tags: ["stupa, ", "pilgrimage, ", "prayer wheels"],
    src: img1,
    year: "1945",
  },
  {
    id: 14,
    name: "Dubdi Monastery",
    location: "Yuksom, West Sikkim, India",
    description:
      "Established in 1701, Dubdi is the oldest monastery in Sikkim and is considered the cradle of Buddhism in the state. It holds great historical and religious significance.",
    tags: ["oldest, ", "historic, ", "Buddhism"],
    src: img2,
    year: "1701",
  },
{
    id: 15,
    name: "Khecheopalri Monastery",
    location: "West Sikkim, India",
    description:
      "Famous for its sacred lake, Khecheopalri Monastery is surrounded by dense forests and considered a wish-fulfilling place by locals and pilgrims alike.",
    tags: ["sacred lake, ", "serene, ", "pilgrimage"],
    src: img3,
    year: "1800",
  },
  {
    id: 16,
    name: "Malam Monastery",
    location: "North Sikkim, India",
    description:
      "Malam Monastery is a remote spiritual center known for its peaceful ambiance, Himalayan views, and local festivals that attract devotees from across the region.",
    tags: ["remote, ", "peaceful, ", "festival"],
    src: img1,
    year: "1900",
  },
  {
  id: 17,
    name: "Line Phagyal Monastery",
    location: "East Sikkim, India",
    description:
      "Line Phagyal is noted for its dedication to traditional Buddhist teachings and for actively engaging the local community in cultural preservation.",
    tags: ["traditional, ", "community, ", "culture"],
    src: img2,
    year: "1920",
  },
  {
    id: 18,
    name: "Karthok Monastery",
    location: "East Sikkim, India",
    description:
      "Karthok Monastery has a rich religious history and is an important center for Buddhist education and cultural preservation in East Sikkim.",
    tags: ["historic, ", "education, ", "culture"],
    src: img3,
    year: "1800",
  },
{
    id: 19,
    name: "Phensang Monastery",
    location: "North Sikkim, India",
    description:
      "Set amidst beautiful landscapes, Phensang Monastery is known for its vibrant religious festivals and dedication to fostering community spiritual life.",
    tags: ["scenic, ", "festivals, ", "community"],
    src: img1,
    year: "1721",
  },
  {
    id: 20,
    name: "Phodong Monastery",
    location: "North Sikkim, India",
    description:
      "One of the oldest and largest monasteries in Sikkim, Phodong is famed for its stunning murals, religious festivals, and its historic significance in the region.",
    tags: ["oldest, ", "murals, ", "festivals"],
    src: img2,
    year: "1740",
  },
  {
    id: 21,
    name: "Labrang Monastery",
    location: "South Sikkim, India",
    description: "Labrang Monastery is a key center for preserving ancient Buddhist traditions and spiritual teachings for the local community.",
    tags: ["ancient, ", "teachings, ", "community"],
    src: img1,
    year: "1850",
  },
  {
    id: 22,
    name: "Tolung Monastery",
    location: "East Sikkim, India",
    description: "Tolung Monastery is known for its scenic beauty and important religious events held throughout the year, attracting many devotees.",
    tags: ["scenic, ", "events, ", "spiritual"],
    src: img2,
    year: "1780",
  },
  {
    id: 23,
    name: "Bermoik Monastery",
    location: "South Sikkim, India",
    description: "Bermoik Monastery is a spiritual center serving the local community and preserving Buddhist teachings and traditions.",
    tags: ["community, ", "Buddhist, ", "teachings"],
    src: img3,
    year: "1875",
  },
  {
  id: 24,
    name: "Dolling Monastery",
    location: "South Sikkim, India",
    description: "Dolling Monastery is known for its serene atmosphere and role in maintaining the spiritual heritage of the region.",
    tags: ["serene, ", "heritage, ", "spiritual"],
    src: img1,
    year: "1890",
  },
  {
    id: 25,
    name: "Yangyang Monastery",
    location: "South Sikkim, India",
    description: "Yangyang Monastery is an important cultural and religious institution known for its traditional Buddhist practices and festivals.",
    tags: ["cultural, ", "traditional, ", "festivals"],
    src: img2,
    year: "1860",
  },
  {
    id: 26,
    name: "Namchi Monastery",
    location: "Namchi, South Sikkim, India",
    description: "Namchi Monastery is a notable religious site in the town of Namchi, famous for its spiritual activities and picturesque surroundings.",
    tags: ["spiritual, ", "picturesque, ", "community"],
    src: img3,
    year: "1900",
  },
{
    id: 27,
    name: "Rinchenpong Monastery",
    location: "Rinchenpong, West Sikkim, India",
    description: "Rinchenpong Monastery offers spiritual teachings amidst stunning landscapes and is cherished for its historic significance in the region.",
    tags: ["historic, ", "scenic, ", "spiritual"],
    src: img1,
    year: "1730",
  },
  {
    id: 28,
    name: "Tingbung Monastery",
    location: "North Sikkim, India",
    description: "Tingbung Monastery is a quiet spiritual retreat known for its community services and peaceful surroundings.",
    tags: ["peaceful, ", "community, ", "retreat"],
    src: img2,
    year: "1885",
  },
  {
    id: 29,
    name: "Burtuk Monastery",
    location: "East Sikkim, India",
    description: "Burtuk Monastery is one of the oldest monasteries in East Sikkim, known for its architectural beauty and religious festivals.",
    tags: ["historic, ", "architecture, ", "festivals"],
    src: img3,
    year: "1750",
  },
{
    id: 30,
    name: "Wok Parbang Monastery",
    location: "North Sikkim, India",
    description: "Wok Parbang Monastery is a prominent spiritual institution in North Sikkim, celebrated for its vibrant ceremonies and cultural significance.",
    tags: ["ceremonies, ", "cultural, ", "spiritual"],
    src: img1,
    year: "1895",
  },
  {
    id: 31,
    name: "Mangbru Monastery",
    location: "North Sikkim, India",
    description: "Mangbru Monastery is a serene spiritual retreat nestled in the highlands of North Sikkim. Known for its peaceful ambiance and traditional Buddhist practices, it serves as a quiet refuge for meditation and community rituals.",
    tags: ["peaceful, ", "traditional, ", "spiritual"],
    src: img2,
    year: "1890",
  },
  {
    id: 32,
    name: "Tsungthang Monastery",
    location: "North Sikkim, India",
    description: "Tsungthang Monastery is a culturally significant site in North Sikkim, revered for its connection to Guru Padmasambhava. It is surrounded by scenic beauty and plays a vital role in preserving local Buddhist heritage and hosting seasonal festivals.",
    tags: ["cultural, ", "heritage, ", "festivals"],
    src: img3,
    year: "1780",
  }
];

export default monasteries;